/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicLayoutRouteImport } from './routes/_public/layout'
import { Route as PrivateLayoutRouteImport } from './routes/_private/layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicAuthLayoutRouteImport } from './routes/_public/_auth/layout'
import { Route as PrivateDashboardIndexRouteImport } from './routes/_private/dashboard/index'
import { Route as PublicAuthSignUpIndexRouteImport } from './routes/_public/_auth/sign-up/index'
import { Route as PublicAuthSignInIndexRouteImport } from './routes/_public/_auth/sign-in/index'
import { Route as PublicAuthForgotIndexRouteImport } from './routes/_public/_auth/forgot/index'
import { Route as PublicAuthActivateIndexRouteImport } from './routes/_public/_auth/activate/index'
import { Route as PublicAuthComponentsGoogleAuthRouteImport } from './routes/_public/_auth/_components/GoogleAuth'

const PublicLayoutRoute = PublicLayoutRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateLayoutRoute = PrivateLayoutRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAuthLayoutRoute = PublicAuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PrivateDashboardIndexRoute = PrivateDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PublicAuthSignUpIndexRoute = PublicAuthSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => PublicAuthLayoutRoute,
} as any)
const PublicAuthSignInIndexRoute = PublicAuthSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => PublicAuthLayoutRoute,
} as any)
const PublicAuthForgotIndexRoute = PublicAuthForgotIndexRouteImport.update({
  id: '/forgot/',
  path: '/forgot/',
  getParentRoute: () => PublicAuthLayoutRoute,
} as any)
const PublicAuthActivateIndexRoute = PublicAuthActivateIndexRouteImport.update({
  id: '/activate/',
  path: '/activate/',
  getParentRoute: () => PublicAuthLayoutRoute,
} as any)
const PublicAuthComponentsGoogleAuthRoute =
  PublicAuthComponentsGoogleAuthRouteImport.update({
    id: '/_components/GoogleAuth',
    path: '/GoogleAuth',
    getParentRoute: () => PublicAuthLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof PrivateDashboardIndexRoute
  '/GoogleAuth': typeof PublicAuthComponentsGoogleAuthRoute
  '/activate': typeof PublicAuthActivateIndexRoute
  '/forgot': typeof PublicAuthForgotIndexRoute
  '/sign-in': typeof PublicAuthSignInIndexRoute
  '/sign-up': typeof PublicAuthSignUpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof PrivateDashboardIndexRoute
  '/GoogleAuth': typeof PublicAuthComponentsGoogleAuthRoute
  '/activate': typeof PublicAuthActivateIndexRoute
  '/forgot': typeof PublicAuthForgotIndexRoute
  '/sign-in': typeof PublicAuthSignInIndexRoute
  '/sign-up': typeof PublicAuthSignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_private': typeof PrivateLayoutRouteWithChildren
  '/_public': typeof PublicLayoutRouteWithChildren
  '/_public/_auth': typeof PublicAuthLayoutRouteWithChildren
  '/_private/dashboard/': typeof PrivateDashboardIndexRoute
  '/_public/_auth/_components/GoogleAuth': typeof PublicAuthComponentsGoogleAuthRoute
  '/_public/_auth/activate/': typeof PublicAuthActivateIndexRoute
  '/_public/_auth/forgot/': typeof PublicAuthForgotIndexRoute
  '/_public/_auth/sign-in/': typeof PublicAuthSignInIndexRoute
  '/_public/_auth/sign-up/': typeof PublicAuthSignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/GoogleAuth'
    | '/activate'
    | '/forgot'
    | '/sign-in'
    | '/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/GoogleAuth'
    | '/activate'
    | '/forgot'
    | '/sign-in'
    | '/sign-up'
  id:
    | '__root__'
    | '/'
    | '/_private'
    | '/_public'
    | '/_public/_auth'
    | '/_private/dashboard/'
    | '/_public/_auth/_components/GoogleAuth'
    | '/_public/_auth/activate/'
    | '/_public/_auth/forgot/'
    | '/_public/_auth/sign-in/'
    | '/_public/_auth/sign-up/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivateLayoutRoute: typeof PrivateLayoutRouteWithChildren
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/_auth': {
      id: '/_public/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicAuthLayoutRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_private/dashboard/': {
      id: '/_private/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PrivateDashboardIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_public/_auth/sign-up/': {
      id: '/_public/_auth/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof PublicAuthSignUpIndexRouteImport
      parentRoute: typeof PublicAuthLayoutRoute
    }
    '/_public/_auth/sign-in/': {
      id: '/_public/_auth/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof PublicAuthSignInIndexRouteImport
      parentRoute: typeof PublicAuthLayoutRoute
    }
    '/_public/_auth/forgot/': {
      id: '/_public/_auth/forgot/'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof PublicAuthForgotIndexRouteImport
      parentRoute: typeof PublicAuthLayoutRoute
    }
    '/_public/_auth/activate/': {
      id: '/_public/_auth/activate/'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof PublicAuthActivateIndexRouteImport
      parentRoute: typeof PublicAuthLayoutRoute
    }
    '/_public/_auth/_components/GoogleAuth': {
      id: '/_public/_auth/_components/GoogleAuth'
      path: '/GoogleAuth'
      fullPath: '/GoogleAuth'
      preLoaderRoute: typeof PublicAuthComponentsGoogleAuthRouteImport
      parentRoute: typeof PublicAuthLayoutRoute
    }
  }
}

interface PrivateLayoutRouteChildren {
  PrivateDashboardIndexRoute: typeof PrivateDashboardIndexRoute
}

const PrivateLayoutRouteChildren: PrivateLayoutRouteChildren = {
  PrivateDashboardIndexRoute: PrivateDashboardIndexRoute,
}

const PrivateLayoutRouteWithChildren = PrivateLayoutRoute._addFileChildren(
  PrivateLayoutRouteChildren,
)

interface PublicAuthLayoutRouteChildren {
  PublicAuthComponentsGoogleAuthRoute: typeof PublicAuthComponentsGoogleAuthRoute
  PublicAuthActivateIndexRoute: typeof PublicAuthActivateIndexRoute
  PublicAuthForgotIndexRoute: typeof PublicAuthForgotIndexRoute
  PublicAuthSignInIndexRoute: typeof PublicAuthSignInIndexRoute
  PublicAuthSignUpIndexRoute: typeof PublicAuthSignUpIndexRoute
}

const PublicAuthLayoutRouteChildren: PublicAuthLayoutRouteChildren = {
  PublicAuthComponentsGoogleAuthRoute: PublicAuthComponentsGoogleAuthRoute,
  PublicAuthActivateIndexRoute: PublicAuthActivateIndexRoute,
  PublicAuthForgotIndexRoute: PublicAuthForgotIndexRoute,
  PublicAuthSignInIndexRoute: PublicAuthSignInIndexRoute,
  PublicAuthSignUpIndexRoute: PublicAuthSignUpIndexRoute,
}

const PublicAuthLayoutRouteWithChildren =
  PublicAuthLayoutRoute._addFileChildren(PublicAuthLayoutRouteChildren)

interface PublicLayoutRouteChildren {
  PublicAuthLayoutRoute: typeof PublicAuthLayoutRouteWithChildren
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublicAuthLayoutRoute: PublicAuthLayoutRouteWithChildren,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivateLayoutRoute: PrivateLayoutRouteWithChildren,
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
